/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from 'drei'
import { PerspectiveCamera } from 'drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/surface.gltf')
  return (
    <group ref={group} {...props} dispose={null} >
      <group position={[1.69, 9.25, -1.84]}>
        <directionalLight intensity={0.6} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-14.39, 3.8, -3.48]} rotation={[1.59, -0.01, 1.69]}>
        <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={22.9} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <mesh material={materials.Material} geometry={nodes.Cube.geometry} />
      <mesh material={materials['Material.001']} geometry={nodes.Sphere.geometry} position={[-5.42, 6.23, 0.58]} />
      <mesh material={materials['Material.002']} geometry={nodes.Suzanne.geometry} position={[-0.36, 3.64, -8.32]} />
    </group>
  )
}

useGLTF.preload('/surface.gltf')
